steps:

- name: "gcr.io/cloud-builder/gcloud"
  args: ['builds', 'submit', '--tag', 'gcr.io/${PROJECT_ID}/api']

- name: "gcr.io/cloud-builder/gcloud"
  args: ['beta', 'run', 'deploy', 'api', '--image',
        'gcr.io/${PROJECT_ID}/api', '--region', 'us-central1',
        '--allow-unauthenticated', 'yes', '--platform', 'managed']